### ISSUE TITLE
BackPort: TLS Support from the original webhook source

### ISSUE THREAD

**Issue by frank-hollmann** [soulteary/webhook#23]
The tls support from the original webhook-server (adnanh) is missing. Please consider a backport. I am aware, that nginx as a reverse proxy could be a solution here, but a reverse proxy ist not always a viable option.

./webhook-adnah -h states: 

-cert string
        path to the HTTPS certificate pem file (default "cert.pem")
-cipher-suites string
        comma-separated list of supported TLS cipher suites
-tls-min-version string
        minimum TLS version (1.0, 1.1, 1.2, 1.3) (default "1.2")

Kind regards.

**Comment by soulteary** [comment]
Thanks for the suggestion, but as you said, it is more appropriate to use Nginx, Traefik, and the cloud service provider's SLB to manage and load certificates. This small project should focus on pure Web Hook processing and business enhancement.
