### ISSUE TITLE
proposal： 提供一个带sh的镜像方便调试

### ISSUE THREAD

**Issue by kevin1sMe** [soulteary/webhook#9]
当前给的镜像都太小了，没有调试能力，想可以ssh进去，并且可能的话，我感觉curl/jq/yq是基本必要的工具。
这个在原本webhook中官方有推荐  thecatlady/webhook 是一致的。

**Comment by zeekzen** [comment]
> 当前给的镜像都太小了，没有调试能力，想可以ssh进去，并且可能的话，我感觉curl/jq/yq是基本必要的工具。 这个在原本webhook中官方有推荐 thecatlady/webhook 是一致的。

原始镜像可能考虑到想剪裁运行镜像的体积，所以内容只有一个证书文件，一个webhook二进制文件，就没别的了，see：https://github.com/soulteary/webhook/blob/10f1b27f52ecf4123dfaf4bcfaf2c71a1d68e45c/docker/Dockerfile.gorelease#L5C1-L6C30
如果有需要，可以基于原始镜像build一个自己的镜像，加上想要的个性化的工具，比如
```dockerfile
FROM soulteary/webhook:3.1.1 as base
FROM alpine:3.19.0
COPY --from=base /usr/bin/webhook /usr/bin/webhook
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
RUN apk add --update --no-cache ca-certificates bash curl wget jq yq
EXPOSE 8345/tcp
CMD webhook
```

```bash
docker build -t webhook-debug:3.1.1 .
```

**Comment by kevin1sMe** [comment]
棒，目前我用的也是自己封装的docker镜像，希望未来可以偷懒：）

**Comment by soulteary** [comment]
<img width="1005" alt="image" src="https://github.com/soulteary/webhook/assets/1500781/426d8470-1a05-40f4-a8c0-2d5704a57c15">

使用 3.2.0 带 extend 的镜像即可。 @zeekzen @kevin1sMe
